name: Subindo Projeto para o servidor

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Get the latest code
        uses: actions/checkout@v2.3.2

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Set Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: 📂 Sync files via FTP (sem vendor)
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/vendor/**           # ✅ NÃO sobe e NÃO apaga mais
            **/.env/**
            **/Codigo Extras/**
          dangerous-clean-slate: false # ✅ Impede remoção de arquivos do servidor
